@startuml
!include commonss

title __COMPANY's Class Diagram__\n

  namespace com.company {
    class Main {
        {static} + main()
    }
  }


    namespace com.repertoire {
      interface com.repertoire.repertoireInfo extends repoModif {
      getName()
      getContent()
      getOwner()
      getSize()
      appendContent()
      setOwner()

      }
    }
    namespace com.repertoire {
          class com.repertoire.Owner {
          Owner(String nom)


          }
        }
    namespace com.repertoire {
          interface com.repertoire.fichierInfo  {
          getName()
          getContent()
          getOwner()
          getSize()
          appendContent()
          setOwner()

          }
        }


     namespace com.repertoire {
        interface com.repertoire.repoModif    {
        addChild()
        getchildren()
        removeChild()
        removeChildren()

        }

  namespace com.factory {
        interface com.factory.FSFactory   {
            createComponent()
        }

        namespace com.factory {
                class com.factory.Composant implements FSFactory   {
                    createComponent()
                }

    namespace com.factory {
                enum com.factory.ComposantType extends Composant   {
                    FICHIER, REPERTOIRE
                }

  com.repertoire.repoModif .right.|> com.factory.FSFactory
  com.repertoire.Owner .up.|> com.factory.Composant
    Main .left.|> com.factory.FSFactory




right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
